version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    working_directory: ~/oneplusbot
    steps:
      - checkout
      - run: msbuild /t:Restore OnePlusBot.sln
      - run: msbuild /t:Build OnePlusBot.sln
  publish:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    working_directory: ~/oneplusbot
    branches:
      only:
        - master
    steps:
      - checkout
      - run: msbuild /t:Restore OnePlusBot.sln
      - run: dotnet publish -c Release -o out-linux -r linux-x64
      - run: git config --global user.name "${GH_NAME}"
      - run: git config --global user.email "${GH_MAIL}"
      - run: cd out-linux
      - run: git add --a
      - run: git commit -m 'Built for Linux'
      - run: git push --force --quiet "https://${GH_ATOKEN}@github.com/Rithari/oneplusbot-linux"> /dev/null 2>&1
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish