version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    working_directory: ~/oneplusbot
    steps:
      - checkout
      - run: msbuild /t:Restore OnePlusBot.sln
      - run: msbuild /t:Build OnePlusBot.sln
workflows:
  version: 2
  build:
    jobs:
      - build